### ISSUE TITLE
ToDoCheckBoxButton Constant 추가

### ISSUE THREAD

**Issue by wood0203** [ToDo-Garden/ToDo-Garden#104]
### 🛠️ 진행할 작업

- ToDoCheckBoxButton에 필요한 레이아웃 관련 상수들을 Constant에 추가합니다.

### 📝 TODO

- [ ] 버튼 Layout 관련 값 추가
- [ ] Animation 속성 관련 값 추가
- [ ] Animation 생성 Layer 객체 UI설정에 필요한 관련 값 추가

### 🗂️ 백로그

- 링크: https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit#gid=1871771583&range=B34
