### ISSUE TITLE
단위 테스트 초기 설정

### ISSUE THREAD

**Issue by noah0316** [ToDo-Garden/ToDo-Garden#14]
### 🛠️ 진행할 작업

- 단위 테스트를 작성하기 위해 설정작업을 진행합니다.
  - Pull request 시 프로젝트의 테스트 코드를 실행하도록 합니다.
  - Pull request 시 프로젝트의 테스트 커버리지를 확인할 수 있도록 합니다.

### 📝 TODO

- [x] Unit test bundle추가
- [x] xctestplan 추가
- [x] Github Actions workflow 추가
- [x] codecov 설정
- [x] Makefile 테스트실행 코드 추가

### 🗂️ 백로그

- 링크: https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit#gid=917831885&range=11:11
