### ISSUE TITLE
RepeatOtherDaysView 추가 

### ISSUE THREAD

**Issue by HG-SONG** [ToDo-Garden/ToDo-Garden#171]
### 🛠️ 진행할 작업

- RepeatOtherDaysView를 추가합니다.

### 📝 TODO

- [ ] ToDoRepeatView 상속받아 추가 기능을 구현합니다.
   - [ ] selected 상태에 따른 view 레이아웃 변경 
   - [ ] subview 상태 관리 구현

### 🗂️ 백로그

- 링크: 
https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit#gid=1871771583
