### ISSUE TITLE
GardenView 추가

### ISSUE THREAD

**Issue by noah0316** [ToDo-Garden/ToDo-Garden#213]
### 🛠️ 진행할 작업

|GardenView|
|--|
|<img width="400" alt="스크린샷 2024-06-05 16 38 20" src="https://github.com/ToDo-Garden/ToDo-Garden/assets/63908856/443e787b-d110-4b82-bd5a-a007f7e8e3d6">|

- 140일간의 뽀모도로 수행 정보를 한 눈에 확인하는 GardenView를 추가합니다.

### 📝 TODO

- [x] GardenView UI 구현
- [x] GardenView 상수 추가
- [x] GardenView 모델 구현

### 🗂️ 백로그

- 링크: [백로그 링크](https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit#gid=136825291&range=B69:B73)
