### ISSUE TITLE
TimerControlButton Style 추가

### ISSUE THREAD

**Issue by noah0316** [ToDo-Garden/ToDo-Garden#23]
### 🛠️ 진행할 작업

<img width="330" alt="Screenshot 2024-02-28 at 7 25 37 PM" src="https://github.com/ToDo-Garden/ToDo-Garden/assets/63908856/ec1ad4f9-beac-4250-a492-0f1f754a9886">

- 타이머를 조작하는 버튼의 스타일을 추가합니다.

### 📝 TODO
- [x] TimerControlButton background image 파일 추가
- [x] UIComponent 모듈 추가
- [x] TimerControlButton 버튼 스타일 추가

### 🗂️ 백로그

- 링크: 
https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit#gid=1871771583&range=37:37
