### ISSUE TITLE
CalendarView 수정

### ISSUE THREAD

**Issue by wood0203** [ToDo-Garden/ToDo-Garden#234]
### 🛠️ 진행할 작업

- CalendarView에 이전 PR #200 에서 요청받았던 수정사항들을 반영합니다.

### 📝 TODO

- [ ] 캘린더 높이 업데이트 애니메이션 끊김 현상 수정
- [ ] 부자연스러운 스크롤 애니메이션 해결
- [ ] 날짜 선택시 셀 색상 변경되지 않는 버그 해결

### 🗂️ 백로그

- 링크: https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit?gid=1871771583#gid=1871771583&range=B2
