### ISSUE TITLE
Utility 패키지 추가

### ISSUE THREAD

**Issue by noah0316** [ToDo-Garden/ToDo-Garden#260]
### 🛠️ 진행할 작업

- 유틸리티 성격의 타입을 가진 패키지를 추가합니다.

### 📝 TODO

- [x] FoundationExtension 패키지 추가
- [x] CombineExtension 패키지 추가
- [x] Utility 패키지 추가

### 🗂️ 백로그

- 링크: x
