### ISSUE TITLE
SettingTimeView 수정 

### ISSUE THREAD

**Issue by HG-SONG** [ToDo-Garden/ToDo-Garden#282]
### 🛠️ 진행할 작업

- SettingTimeView 수정 

### 📝 TODO

- [ ] 최소 설정가능 시간 "10분" 으로 설정
- [ ] Date값 사용가능한 형식으로 수정
- [ ] 서브뷰 배치 수정  

### 🗂️ 백로그

- 링크:
