### ISSUE TITLE
ShareGarden ViewController 구현

### ISSUE THREAD

**Issue by noah0316** [ToDo-Garden/ToDo-Garden#298]
### 🛠️ 진행할 작업
- ShareGardenViewController를 구현합니다.

### 📝 TODO
- [x] 나의 가든  
  - [x] 나의 가든 우측에는 공유 버튼이 존재한다.
  - [x] 상단에는 프로필 정보를 표시하는 뷰가 존재한다.
  - [x] 프로필 정보 아래에는 가든 정보를 표시하는 뷰가 존재한다.

- [x] #431
  - [x] 친구의 가든 우측에는 편집 버튼이 존재한다.
  - [x] 친구의 가든을 검색하는 서치바가 존재한다.
  - [x] 서치바 아래에는 친구의 가든 목록을 불러오는 뷰가 존재한다.
  - [x] 친구 가든을 삭제할 수 있는 버튼이 존재한다.

### 🗂️ 백로그

- [링크](https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit?gid=917831885#gid=917831885&range=A117:A145)
