### ISSUE TITLE
ShareGarden Interactor 구현

### ISSUE THREAD

**Issue by noah0316** [ToDo-Garden/ToDo-Garden#299]
### 🛠️ 진행할 작업

- ShareGardenScene ViewController의 이벤트 의도에 따른 올바른 logic을 구현합니다.

### 📝 TODO
- [x] 프로필 정보를 불러오는 로직을 구현한다.
- [x] 나의 가든 정보를 불러오는 로직을 구현한다.
- [x] 친구 가든 목록 정보를 불러오는 로직을 구현한다.
- [x] 친구 가든 삭제를 요청하는 로직을 구현한다.
- [ ] 예외 처리

### 🗂️ 백로그

- [링크](https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit?gid=917831885#gid=917831885&range=A117:A145)
