### ISSUE TITLE
ShareGarden Presenter 구현

### ISSUE THREAD

**Issue by noah0316** [ToDo-Garden/ToDo-Garden#300]
### 🛠️ 진행할 작업
- Interactor를 통해 받은 Response를 View에 표시하기 위한 형태로 가공합니다.

### 📝 TODO
- [x] Response로 받은 프로필 정보를 viewController에 전달한다.
- [x] Response로 받은 나의 가든 정보를 viewController에 전달한다.
- [x] Response로 받은 친구 가든 목록 정보를 displayedFriendInfos 배열로 전환해 viewController에 전달한다.
- [x] Response로 받은 친구 가든 삭제 성공 여부를 ViewController에 전달한다.

### 🗂️ 백로그

- [링크](https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit?gid=917831885#gid=917831885&range=A117:A145)
