### ISSUE TITLE
ShareGarden Router 구현

### ISSUE THREAD

**Issue by noah0316** [ToDo-Garden/ToDo-Garden#301]
### 🛠️ 진행할 작업
- ShareGardenScene에서 다른 화면으로 화면전환하는 기능을 구현합니다.

### 📝 TODO
- [ ] ShareGardenToInstaViewController로 전환하는 로직을 구현한다.
  - [ ] 화면 전환시, 프로필 이미지와 이름, 연속 기록 정보를 전달한다.
- [ ] StatisticsViewController로 전환하는 로직을 구현한다.
  - [ ] 통계보기 화면으로 전환할 때 나의 가든 정보를 전달한다.
- [ ] SearchFriendGardenViewController로 전환하는 로직을 구현한다.

### 🗂️ 백로그

- [링크](https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit?gid=917831885#gid=917831885&range=A117:A145)
