### ISSUE TITLE
ManageGroupModels 추가

### ISSUE THREAD

**Issue by HG-SONG** [ToDo-Garden/ToDo-Garden#323]
### 🛠️ 진행할 작업

- 스켈레톤 코드였던 ManageGroupModels를 수정합니다. 

### 📝 TODO

- [ ] ToDoGroup 에 대한 뷰모델 구현 
- [ ] Fetch useCase에 필요한 모델 구현 
- [ ] Delete useCase에 필요한 모델 구현 
- [ ] Reorder useCase에 필요한 모델 구현 

### 🗂️ 백로그

- 링크:
