### ISSUE TITLE
GroupSelectionView 수정

### ISSUE THREAD

**Issue by wood0203** [ToDo-Garden/ToDo-Garden#377]
### 🛠️ 진행할 작업

- reladted: #374
- [리뷰](https://github.com/ToDo-Garden/ToDo-Garden/pull/374#pullrequestreview-2198333395)에서 언급되었던 GroupSelectionView의 UI 버그들을 수정합니다.

### 📝 TODO

- [ ] 셀 삽입/삭제 애니메이션 통일
- [ ] Cell SeparatorLine 레이아웃 버그 해결
- [ ] TableView HeaderView 최상단 고정

### 🗂️ 백로그

- 링크: https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit?gid=1871771583#gid=1871771583&range=B24
