### ISSUE TITLE
PostGroupScene(2) - useCase 동작 흐름 구현

### ISSUE THREAD

**Issue by HG-SONG** [ToDo-Garden/ToDo-Garden#379]
### 🛠️ 진행할 작업

- PostGroupScene(2) - useCase 동작 흐름 구현

### 📝 TODO

- [ ] 색상 업데이트 구현 
- [ ] 페이로드에 따른 올바른 view 초기 표시상태 구현
- [ ] 완료버튼 Enable / Disable

### 🗂️ 백로그

- 링크:
