### ISSUE TITLE
SettingViewController UI 하위 뷰 추가

### ISSUE THREAD

**Issue by wood0203** [ToDo-Garden/ToDo-Garden#405]
### 🛠️ 진행할 작업

- SettingViewController UI 구현에 필요한 서브뷰들을 추가합니다.
- 구현할 서브뷰들의 목록입니다.

|서브뷰 이름|이미지|
|---|---|
|이용가이드 버튼|<img width="404" alt="스크린샷 2024-08-06 23 04 29" src="https://github.com/user-attachments/assets/55787027-e5af-4820-af9b-778f54b89d40">|
|사용자 설정|<img width="400" alt="스크린샷 2024-08-06 23 04 33" src="https://github.com/user-attachments/assets/e83d3a46-96d8-4da7-9723-93b0295ccd6e">|
|앱 지원|<img width="300" alt="스크린샷 2024-08-06 23 04 38" src="https://github.com/user-attachments/assets/e754214e-d5d3-4570-ba34-5ccae72c0d58">|
|버전 정보|<img width="405" alt="스크린샷 2024-08-06 23 04 46" src="https://github.com/user-attachments/assets/ca958fd9-aa98-4799-bcbe-5fd2279f0087">|

### 📝 TODO

- [ ] 이용가이드 버튼 추가
- [ ] 사용자 설정 버튼 추가
- [ ] 앱 지원 버튼 추가
- [ ] 버전 정보 및 업데이트 뷰 추가

### 🗂️ 백로그

- 링크: https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit?gid=917831885#gid=917831885&range=B168

### ⚙️ 기타

- UI와 관련된 작업을 하나의 PR에서 하기에는 작업이 많아 하위 뷰들만 해당 PR에서 추가합니다.
