### ISSUE TITLE
SettingScene 컴포넌트 필요 이미지 추가

### ISSUE THREAD

**Issue by wood0203** [ToDo-Garden/ToDo-Garden#406]
### 🛠️ 진행할 작업

- ToDoGardenUI 패키지에 SettingScene에서 사용되는 이미지들을 추가합니다.
- 추가할 이미지들은 다음과 같습니다.

|프로필 기본 이미지|투두가든 로고 이미지|나뭇잎 이미지|
|--|--|--|
|<img width="100" src="https://github.com/user-attachments/assets/b9b94374-6a16-4ed6-a764-2f682fac1837">|![toDoGarden_logo_image@3x](https://github.com/user-attachments/assets/86e5f886-3ab2-4e5d-af89-62f929885391)|![leaf_Image@3x](https://github.com/user-attachments/assets/b71b7ce4-5197-4116-bc48-392290031ba2)|

### 📝 TODO

- [x] 프로필 기본 이미지 추가
- [x] 투두가든 로고 이미지 추가
- [x] 나뭇잎 이미지 추가

### 🗂️ 백로그

- 링크: https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit?gid=917831885#gid=917831885&range=B168
