### ISSUE TITLE
EditToDoInteractor 테스트 작성

### ISSUE THREAD

**Issue by wood0203** [ToDo-Garden/ToDo-Garden#414]
### 🛠️ 진행할 작업

- EditToDoInteractor 테스트 코드를 작성합니다.

### 📝 TODO

- [x] EditToDoScene 테스트 타겟 추가
- [x] EditToDoInteractor 테스트 작성
- [x] EditToDoInteractor 누락된 비즈니스 로직 추가
- [x] Worker 프로토콜 추상화

### 🗂️ 백로그

- 링크: https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit?gid=917831885#gid=917831885&range=B82
