### ISSUE TITLE
Feat: Styled Row 추가 구현

### ISSUE THREAD

**Issue by GangWoon** [ToDo-Garden/ToDo-Garden#439]
### 📝 TODO

- [x] 1. 디자인과 다르게 x center가 맞지 않는 문제
- [x]  2. garden info 프로필 기본이미지가 다르게 설정되어있는 문제
    1. default parameter가 잘못설정되어있는 것으로 추정
    2. (스크린샷 상으로는 강제로 수정한 버전)
- [x]  3. 프로필 사이즈가 맞지 않는 문제
    1. 프로필 사이즈가 통일되어있음
    2. garden info에서는 프로필 사이즈가 달라야함
- [x]  4. forward image 버튼을 회전시킬 수 있어야하는데 ⇒ 특정이 가능한지

### 🗂️ 백로그

- 링크:
