### ISSUE TITLE
CheckBox 추가

### ISSUE THREAD

**Issue by wood0203** [ToDo-Garden/ToDo-Garden#46]
### 🛠️ 진행할 작업

<img width="96" alt="스크린샷 2024-03-07 14 13 49" src="https://github.com/ToDo-Garden/ToDo-Garden/assets/84387335/f2d0da2a-c55f-46d9-90a6-22d6a714a6ec">
<img width="93" alt="스크린샷 2024-03-07 14 13 40" src="https://github.com/ToDo-Garden/ToDo-Garden/assets/84387335/d6b98a4e-c039-4c7e-ae7a-afa02ea02c5e">

- 투두를 완료 처리할 때 사용하는 체크박스 컴포넌트를 추가합니다.

### 📝 TODO

- [ ] CheckBox 컴포넌트 추가
- [ ] 완료 / 미완료 상태 구현
- [ ] 완료 선택시 애니메이션 구현
- [ ] 그룹 색상에 따라 테두리 색상 변경 가능하도록 구현

### 🗂️ 백로그

- 링크: [백로그](https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit#gid=1871771583&range=B35)
