### ISSUE TITLE
ManageGroupScene , PostGroupScene 수정 

### ISSUE THREAD

**Issue by HG-SONG** [ToDo-Garden/ToDo-Garden#471]
### 🛠️ 진행할 작업

- ManageGroupScene , PostGroupScene에 속한 파일들을 일부 수정합니다.

### 📝 TODO

- [ ] "그룹편집" , "그룹추가" Constant를 추가합니다. 
- [ ] PostGroup으로 진입할 때, 페이로드로써 groupId, groupName, groupColor 를 전달합니다. 
- [ ] 일부 메서드의 파라미터/ 이름을 수정합니다. 

### 🗂️ 백로그

- 링크:
