### ISSUE TITLE
UserInfoScene VIP 구현

### ISSUE THREAD

**Issue by wood0203** [ToDo-Garden/ToDo-Garden#481]
### 🛠️ 진행할 작업

- 유저정보 화면의 VIP를 구현합니다.

### 📝 TODO

- [x] UserInfoScene 로그아웃 VIP 구현
- [x] UserInfoScene 회원탈퇴 VIP 구현
- [x] UserInfoScene 유저 정보 Fetch VIP 구현

### 🗂️ 백로그

- [DEV 백로그](https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit?gid=917831885#gid=917831885&range=B174)
- [화면 기술서](https://www.notion.so/65a0d6c239334afbbfe5a68fef9162a8?pvs=4)
