### ISSUE TITLE
ToDoGardenBoxButtonConstant 추가 

### ISSUE THREAD

**Issue by HG-SONG** [ToDo-Garden/ToDo-Garden#49]
### 🛠️ 진행할 작업

- ToDoGardenUIConstant에 ToDoGardenBoxButtonConstant를 추가합니다. 

### 📝 TODO

- [x] Size에 필요한 Constant 
- [x] Alpha에 필요한 Constant
- [x] Constant.ToDoGardenBoxButton.something ... 으로 접근 가능하게 구성하기 

### 🗂️ 백로그

- 링크: https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit#gid=1871771583
