### ISSUE TITLE
EditUserNameSceneViewController UI 추가

### ISSUE THREAD

**Issue by wood0203** [ToDo-Garden/ToDo-Garden#500]
### 🛠️ 진행할 작업

- Figma 디자인에 맞게 EditUserNameSceneViewController UI를 구현합니다.
- 구현할 UI는 아래와 같습니다.

<img width="250" src="https://github.com/user-attachments/assets/e9294945-b56a-41fb-8cac-f76f546b2328">

### 📝 TODO

- [ ] 완료 네비게이션 BarbuttonItem 추가
- [ ] 닉네임 입력 View 추가
- [ ] 닉네임 입력조건 Label 추가

### 🗂️ 백로그

- 링크: https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit?gid=917831885#gid=917831885&range=B182
