### ISSUE TITLE
EditUserNameScene VIP 사이클 추가

### ISSUE THREAD

**Issue by wood0203** [ToDo-Garden/ToDo-Garden#509]
### 🛠️ 진행할 작업

- EditUserNameScene에 필요한 VIP 사이클들을 추가합니다.

### 📝 TODO

- [x] 닉네임 입력 VIP
- [x] Payload 전달받은 닉네임 출력 VIP
- [x] 닉네임 수정 요청 VIP

### 🗂️ 백로그

- 링크: https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit?gid=917831885#gid=917831885&range=B182
- 개발 기술서: https://www.notion.so/6e420303e66e43e68479f6be136554cf?pvs=4
