### ISSUE TITLE
애플로그인 버튼 수정 

### ISSUE THREAD

**Issue by HG-SONG** [ToDo-Garden/ToDo-Garden#519]
### 🛠️ 진행할 작업

- 애플로그인 버튼을 수정합니다.

### 📝 TODO

- [ ] height 44에 font 19 로 변경 
- [ ] 애플로고의 레이아웃 제약을 수정합니다. 
- [ ] 터치이벤트를 감지하면 강조효과를 표시합니다.

### 🗂️ 백로그

- 링크:
