### ISSUE TITLE
UserInfoScene 유저 소개 리로드 Business Logic 추가 

### ISSUE THREAD

**Issue by wood0203** [ToDo-Garden/ToDo-Garden#604]
### 🛠️ 진행할 작업

- 유저 소개화면에서 수정된 소개글로 리로드하는 비즈니스 로직을 추가합니다.

<img width="250" src="https://github.com/user-attachments/assets/4f49d50b-944c-4bda-98a8-d1f71b66ceb2">

### 📝 TODO

- [x] Business Logic 추가
- [x] 소개글 전달 Presentation Logic 추가
- [x] 소개글 없을 때 호출할 Presentation Logic 추가

### 🗂️ 백로그

- 링크: https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit?gid=917831885#gid=917831885&range=B174
