### ISSUE TITLE
Login <-> SignUp 라우팅 구현 : LoginScene

### ISSUE THREAD

**Issue by HG-SONG** [ToDo-Garden/ToDo-Garden#624]
### 🛠️ 진행할 작업

- 로그인 <-> 사인업 라우팅 

### 📝 TODO

- [x] 로그인씬과 사인업씬을 이어붙입니다. 
- [x] 올바른 페이로드값을 전달합니다.
- [x] 내비게이션 바 표시 / 미표시를 설정합니다. 

### 🗂️ 백로그

- 링크:
