### ISSUE TITLE
ProfileImageView 기본 이미지 추가

### ISSUE THREAD

**Issue by wood0203** [ToDo-Garden/ToDo-Garden#63]
### 🛠️ 진행할 작업

- ToDoGardenUIResource 타겟에 ProfileImageView의 기본 이미지들을 추가합니다.
- 추가할 이미지들은 다음과 같습니다.

|친구의 가든 목록용|프로필 & 설정 & 공유 탭 화면|
|---|---|
|<img src="https://github.com/ToDo-Garden/ToDo-Garden/assets/84387335/ef9ea64a-c1ca-40f7-aa2a-63107d7c2670" width="108" height="108">|<img src="https://github.com/ToDo-Garden/ToDo-Garden/assets/84387335/678152c6-04f5-493e-9ae5-ae96f3381c6d" width="108" height="108">|

### 📝 TODO

- [ ] 친구 가든 목록용 이미지 추가
- [ ] 기본 이미지 추가
- [ ] UIImage Extension 추가

### 🗂️ 백로그

- 링크: https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit#gid=1871771583&range=B34
