### ISSUE TITLE
UserInfoScene 수정된 닉네임 리로드 VIP 추가

### ISSUE THREAD

**Issue by wood0203** [ToDo-Garden/ToDo-Garden#634]
### 🛠️ 진행할 작업

- 닉네임 수정화면에서 수정된 닉네임을 리로드하는 VIP를 추가합니다.

### 동작 GIF

<img width="300" src="https://github.com/user-attachments/assets/8bafb748-c684-44df-8e10-7fe612d52921">

### 📝 TODO

- [ ] Business Logic 추가
- [ ] Presenter Logic 추가
- [ ] Display Logic 추가

### 🗂️ 백로그

- 링크: https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit?gid=917831885#gid=917831885&range=B174
