### ISSUE TITLE
BubbleLabel 추가 

### ISSUE THREAD

**Issue by HG-SONG** [ToDo-Garden/ToDo-Garden#648]
### 🛠️ 진행할 작업

- BubbleLabel 추가 

### 📝 TODO

- [x] 내부 텍스트 크기에 맞게 말풍선이 동적으로 늘어나야함
- [x] 말풍선 꼬리의 위치와 크기는 동일해야함. 
- [x] 텍스트 첫번째 라인 첫번째 칸에는 image가 글자처럼 취급되어 삽입되어야 함
- [x] BubbleLabel 우측에 cancelButton이 존재해야함
- [x] BubbleLabel를 사용하는 측(caller)에서 cancelButton에 대한 액션을 정의할 수 있어야함

### 🗂️ 백로그

- 링크:
