### ISSUE TITLE
PeriodSegmentedControlAppearance 추가 

### ISSUE THREAD

**Issue by HG-SONG** [ToDo-Garden/ToDo-Garden#65]
### 🛠️ 진행할 작업

- PeriodSegmentedControl의 **subview**로 사용될 PeriodSegmentedControlBaseView를 만들고, 추가합니다.

### 📝 TODO

- [ ] 표시될 label에 대하여 
   - 생성 및 레이아웃 정의 
   - 커스텀 텍스트를 넣거나, 개수 변경 가능
- [ ] 표시될 indicatorView에 대하여
   - 생성 및 레이아웃 정의 
   - 좌표 이동에 대한 동작 정의 
   - 커스텀 이미지를 indicatorView의 이미지로 사용할 수 있음 
- [ ] 표시될 backgroundView 생성 및 정의
   - 생성 및 레이아웃 정의 
   - 커스텀 이미지를 backgroundView의 이미지로 사용할 수 있음

### 🗂️ 백로그

- 링크: 
https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit#gid=1871771583
