### ISSUE TITLE
MyStatsScene VIP 구현 전 사전준비 

### ISSUE THREAD

**Issue by HG-SONG** [ToDo-Garden/ToDo-Garden#688]
### 🛠️ 진행할 작업

- MyStatsScene VIP흐름 구현 전 사전준비를 합니다. 

### 📝 TODO

- [ ] MyStatsView 레이아웃 설정
- [ ] 엔터티 모델 정의 
- [ ] 템플릿에서 자동생성된 속성이름 및 타입 변경

### 🗂️ 백로그

- 링크:
