### ISSUE TITLE
ToDoGardenPlainButton 공유 탭에서 사용하는 이미지 추가

### ISSUE THREAD

**Issue by wood0203** [ToDo-Garden/ToDo-Garden#87]
### 🛠️ 진행할 작업

- 공유 탭에서 ToDoGardenPlainButton 구현시 필요한 이미지들을 추가합니다.

1. 아래 화살표 이미지 (친구 가든 목록에서 사용)
<img width="404" alt="스크린샷 2024-04-23 15 57 04" src="https://github.com/ToDo-Garden/ToDo-Garden/assets/84387335/6345fbd1-85ba-4aa3-b760-8f2d4d0a1763">

---

2. 뽀모 정보 버튼 이미지
3. 닫기 버튼 이미지
<img width="539" alt="스크린샷 2024-04-23 15 57 29" src="https://github.com/ToDo-Garden/ToDo-Garden/assets/84387335/3f40739a-3554-4922-b128-9a8d7a2c5b18">

### 📝 TODO

- [ ] 뽀모 정보 버튼 이미지 추가
- [ ] 아래로 펼쳐보기 이미지 추가
- [ ] 닫기 버튼 이미지

### 🗂️ 백로그

- 링크: https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit#gid=1871771583&range=B47
